# Generated by Django 4.0.4 on 2022-05-19 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0003_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreoGeneracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('generacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacion1.alumno')),
            ],
        ),
    ]
