# Generated by Django 4.0.4 on 2022-05-19 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0004_correogeneracion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CorreoGeneracion',
        ),
    ]
