# Generated by Django 4.0.4 on 2022-05-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0005_delete_correogeneracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(max_length=500)),
                ('imagen', models.ImageField(blank=True, default='logo.png', null=True, upload_to='foto_prod')),
            ],
        ),
    ]
