# Generated by Django 4.0.4 on 2022-05-23 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0006_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foto',
            old_name='mensaje',
            new_name='descripcion',
        ),
    ]
