# Generated by Django 4.0.4 on 2022-05-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0007_rename_mensaje_foto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='imagen',
            field=models.ImageField(blank=True, default='logoSIV.png', null=True, upload_to='fotos'),
        ),
    ]
