# Generated by Django 4.0.4 on 2022-05-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0008_alter_foto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='descripcion',
            field=models.TextField(max_length=100),
        ),
    ]
