# Generated by Django 4.0.4 on 2022-05-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0009_alter_foto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
