# Generated by Django 4.0.4 on 2022-05-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion1', '0010_alter_foto_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='generacion',
        ),
        migrations.AddField(
            model_name='alumno',
            name='rut',
            field=models.CharField(default=' ', max_length=15),
            preserve_default=False,
        ),
    ]
